pipelineJob('CCSM_NFT_dailyTriggers') {
    description('CCSM NFT daily triggers job')

    logRotator(-1, 15, 1, -1)

    authorization {
        permission('hudson.model.Item.Read:authenticated')
    }

    parameters {
        stringParam('UDM_AUSF_EIR_RELEASE__TIME', "", "Format: yyyy-MM-dd HH:mm")
        stringParam('UDM_AUSF_EIR_RELEASE__NFT_VERSION', ccsm_default_params['udm_nft_auto_version']['value'], "")
        stringParam('UDM_AUSF_EIR_RELEASE__NFT_BRANCH', ccsm_default_params['nft_branch']['value'], "")
        stringParam('UDM_AUSF_EIR_RELEASE__CCSM', ccsm_default_params['ccsm_package']['value'], "")
        stringParam('UDM_AUSF_EIR_RELEASE__SMESH', ccsm_default_params['smesh_package']['value'], "")
        booleanParam("UDM_AUSF_EIR_RELEASE__${ccsm_default_params['run_trafficmix']['name']}", ccsm_default_params['run_trafficmix']['value'].toBoolean(), "")
        booleanParam("UDM_AUSF_EIR_RELEASE__${ccsm_default_params['run_stability']['name']}", ccsm_default_params['run_stability']['value'].toBoolean(), "")
        booleanParam("UDM_AUSF_EIR_RELEASE__${ccsm_default_params['run_maintainability']['name']}", ccsm_default_params['run_maintainability']['value'].toBoolean(), "")
        booleanParam("UDM_AUSF_EIR_RELEASE__${ccsm_default_params['run_podsfaults']['name']}", ccsm_default_params['run_podsfaults']['value'].toBoolean(), "")
        booleanParam("UDM_AUSF_EIR_RELEASE__${ccsm_default_params['run_commonfailures']['name']}", ccsm_default_params['run_commonfailures']['value'].toBoolean(), "")
        booleanParam("UDM_AUSF_EIR_RELEASE__${ccsm_default_params['run_licenses']['name']}", ccsm_default_params['run_licenses']['value'].toBoolean(), "")
        booleanParam("UDM_AUSF_EIR_RELEASE__${ccsm_default_params['run_overload_tcs']['name']}", ccsm_default_params['run_overload_tcs']['value'].toBoolean(), "")
        extendedChoice {
            name("UDM_AUSF_EIR_RELEASE__CLOUD")
            type("PT_SINGLE_SELECT")
            value(ccsm_default_params['cloud']['value'])
            projectName("")
            propertyFile("")
            groovyScript("")
            groovyScriptFile("")
            bindings("")
            groovyClasspath("")
            propertyKey("")
            defaultValue(ccsm_default_params['cloud']['default_value'])
            defaultPropertyFile("")
            defaultGroovyScript("")
            defaultGroovyScriptFile("")
            defaultBindings("")
            defaultGroovyClasspath("")
            defaultPropertyKey("")
            descriptionPropertyValue(ccsm_default_params['cloud']['value_description'])
            descriptionPropertyFile("")
            descriptionGroovyScript("")
            descriptionGroovyScriptFile("")
            descriptionBindings("")
            descriptionGroovyClasspath("")
            descriptionPropertyKey("")
            javascriptFile("")
            javascript("")
            saveJSONParameterToFile(false)
            quoteValue(false)
            visibleItemCount(1)
            description("\n______________________________________________________________________________________________________\n")
            multiSelectDelimiter(',')
        }
        stringParam('UDM_AUSF_EIR_RELEASE_IPV6__TIME', "", "Format: yyyy-MM-dd HH:mm")
        stringParam('UDM_AUSF_EIR_RELEASE_IPV6__NFT_VERSION', ccsm_default_params['udm_nft_auto_version']['value'], "")
        stringParam('UDM_AUSF_EIR_RELEASE_IPV6__NFT_BRANCH', ccsm_default_params['nft_branch']['value'], "")
        stringParam('UDM_AUSF_EIR_RELEASE_IPV6__CCSM', ccsm_default_params['ccsm_package']['value'], "")
        stringParam('UDM_AUSF_EIR_RELEASE_IPV6__SMESH', ccsm_default_params['smesh_package']['value'], "")
        booleanParam("UDM_AUSF_EIR_RELEASE_IPV6__${ccsm_default_params['run_trafficmix']['name']}", ccsm_default_params['run_trafficmix']['value'].toBoolean(), "")
        booleanParam("UDM_AUSF_EIR_RELEASE_IPV6__${ccsm_default_params['run_stability']['name']}", ccsm_default_params['run_stability']['value'].toBoolean(), "")
        booleanParam("UDM_AUSF_EIR_RELEASE_IPV6__${ccsm_default_params['run_maintainability']['name']}", ccsm_default_params['run_maintainability']['value'].toBoolean(), "")
        booleanParam("UDM_AUSF_EIR_RELEASE_IPV6__${ccsm_default_params['run_podsfaults']['name']}", ccsm_default_params['run_podsfaults']['value'].toBoolean(), "")
        booleanParam("UDM_AUSF_EIR_RELEASE_IPV6__${ccsm_default_params['run_commonfailures']['name']}", ccsm_default_params['run_commonfailures']['value'].toBoolean(), "")
        booleanParam("UDM_AUSF_EIR_RELEASE_IPV6__${ccsm_default_params['run_licenses']['name']}", ccsm_default_params['run_licenses']['value'].toBoolean(), "")
        booleanParam("UDM_AUSF_EIR_RELEASE_IPV6__${ccsm_default_params['run_overload_tcs']['name']}", ccsm_default_params['run_overload_tcs']['value'].toBoolean(), "")
        extendedChoice {
            name("UDM_AUSF_EIR_RELEASE_IPV6__CLOUD")
            type("PT_SINGLE_SELECT")
            value(ccsm_default_params['cloud_ipv6']['value'])
            projectName("")
            propertyFile("")
            groovyScript("")
            groovyScriptFile("")
            bindings("")
            groovyClasspath("")
            propertyKey("")
            defaultValue(ccsm_default_params['cloud_ipv6']['default_value'])
            defaultPropertyFile("")
            defaultGroovyScript("")
            defaultGroovyScriptFile("")
            defaultBindings("")
            defaultGroovyClasspath("")
            defaultPropertyKey("")
            descriptionPropertyValue(ccsm_default_params['cloud_ipv6']['value_description'])
            descriptionPropertyFile("")
            descriptionGroovyScript("")
            descriptionGroovyScriptFile("")
            descriptionBindings("")
            descriptionGroovyClasspath("")
            descriptionPropertyKey("")
            javascriptFile("")
            javascript("")
            saveJSONParameterToFile(false)
            quoteValue(false)
            visibleItemCount(1)
            description("\n______________________________________________________________________________________________________\n")
            multiSelectDelimiter(',')
        }
        stringParam('UDM_AUSF_EIR_RELEASE_CLEAR__TIME', "", "Format: yyyy-MM-dd HH:mm")
        stringParam('UDM_AUSF_EIR_RELEASE_CLEAR__NFT_VERSION', ccsm_default_params['udm_nft_auto_version']['value'], "")
        stringParam('UDM_AUSF_EIR_RELEASE_CLEAR__NFT_BRANCH', ccsm_default_params['nft_branch']['value'], "")
        stringParam('UDM_AUSF_EIR_RELEASE_CLEAR__CCSM', ccsm_default_params['ccsm_package']['value'], "")
        stringParam('UDM_AUSF_EIR_RELEASE_CLEAR__SMESH', ccsm_default_params['smesh_package']['value'], "")
        booleanParam("UDM_AUSF_EIR_RELEASE_CLEAR__${ccsm_default_params['run_trafficmix']['name']}", ccsm_default_params['run_trafficmix']['value'].toBoolean(), "")
        booleanParam("UDM_AUSF_EIR_RELEASE_CLEAR__${ccsm_default_params['run_stability']['name']}", ccsm_default_params['run_stability']['value'].toBoolean(), "")
        booleanParam("UDM_AUSF_EIR_RELEASE_CLEAR__${ccsm_default_params['run_maintainability']['name']}", ccsm_default_params['run_maintainability']['value'].toBoolean(), "")
        booleanParam("UDM_AUSF_EIR_RELEASE_CLEAR__${ccsm_default_params['run_podsfaults']['name']}", ccsm_default_params['run_podsfaults']['value'].toBoolean(), "")
        booleanParam("UDM_AUSF_EIR_RELEASE_CLEAR__${ccsm_default_params['run_commonfailures']['name']}", ccsm_default_params['run_commonfailures']['value'].toBoolean(), "")
        booleanParam("UDM_AUSF_EIR_RELEASE_CLEAR__${ccsm_default_params['run_licenses']['name']}", ccsm_default_params['run_licenses']['value'].toBoolean(), "")
        booleanParam("UDM_AUSF_EIR_RELEASE_CLEAR__${ccsm_default_params['run_overload_tcs']['name']}", ccsm_default_params['run_overload_tcs']['value'].toBoolean(), "")
        extendedChoice {
            name("UDM_AUSF_EIR_RELEASE_CLEAR__CLOUD")
            type("PT_SINGLE_SELECT")
            value(ccsm_default_params['cloud']['value'])
            projectName("")
            propertyFile("")
            groovyScript("")
            groovyScriptFile("")
            bindings("")
            groovyClasspath("")
            propertyKey("")
            defaultValue(ccsm_default_params['cloud']['default_value'])
            defaultPropertyFile("")
            defaultGroovyScript("")
            defaultGroovyScriptFile("")
            defaultBindings("")
            defaultGroovyClasspath("")
            defaultPropertyKey("")
            descriptionPropertyValue(ccsm_default_params['cloud']['value_description'])
            descriptionPropertyFile("")
            descriptionGroovyScript("")
            descriptionGroovyScriptFile("")
            descriptionBindings("")
            descriptionGroovyClasspath("")
            descriptionPropertyKey("")
            javascriptFile("")
            javascript("")
            saveJSONParameterToFile(false)
            quoteValue(false)
            visibleItemCount(1)
            description("\n______________________________________________________________________________________________________\n")
            multiSelectDelimiter(',')
        }
        stringParam('UDM_AUSF_EIR_INTERNAL__TIME', "", "Format: yyyy-MM-dd HH:mm")
        stringParam('UDM_AUSF_EIR_INTERNAL__NFT_VERSION', ccsm_default_params['udm_nft_auto_version']['value'], "")
        stringParam('UDM_AUSF_EIR_INTERNAL__NFT_BRANCH', ccsm_default_params['nft_branch']['value'], "")
        stringParam('UDM_AUSF_EIR_INTERNAL__CCSM', ccsm_default_params['ccsm_package']['value'], "")
        stringParam('UDM_AUSF_EIR_INTERNAL__SMESH', ccsm_default_params['smesh_package']['value'], "")
        booleanParam("UDM_AUSF_EIR_INTERNAL__${ccsm_default_params['run_trafficmix']['name']}", ccsm_default_params['run_trafficmix']['value'].toBoolean(), "")
        booleanParam("UDM_AUSF_EIR_INTERNAL__${ccsm_default_params['run_stability']['name']}", ccsm_default_params['run_stability']['value'].toBoolean(), "")
        booleanParam("UDM_AUSF_EIR_INTERNAL__${ccsm_default_params['run_maintainability']['name']}", ccsm_default_params['run_maintainability']['value'].toBoolean(), "")
        booleanParam("UDM_AUSF_EIR_INTERNAL__RUN_ROBUSTNESS_INTERNAL", true, "")
        booleanParam("UDM_AUSF_EIR_INTERNAL__RUN_ROBUSTNESS_INPROGRESS", ccsm_default_params['run_robustness']['value'].toBoolean(), "")
        booleanParam("UDM_AUSF_EIR_INTERNAL__RUN_ROBUSTNESS_RELEASE", ccsm_default_params['run_robustness']['value'].toBoolean(), "")
        booleanParam("UDM_AUSF_EIR_INTERNAL__${ccsm_default_params['run_podsfaults']['name']}", ccsm_default_params['run_podsfaults']['value'].toBoolean(), "")
        booleanParam("UDM_AUSF_EIR_INTERNAL__${ccsm_default_params['run_commonfailures']['name']}", ccsm_default_params['run_commonfailures']['value'].toBoolean(), "")
        booleanParam("UDM_AUSF_EIR_INTERNAL__${ccsm_default_params['run_licenses']['name']}", ccsm_default_params['run_licenses']['value'].toBoolean(), "")
        booleanParam("UDM_AUSF_EIR_INTERNAL__${ccsm_default_params['run_overload_tcs']['name']}", ccsm_default_params['run_overload_tcs']['value'].toBoolean(), "")
        extendedChoice {
            name("UDM_AUSF_EIR_INTERNAL__CLOUD")
            type("PT_SINGLE_SELECT")
            value(ccsm_default_params['cloud']['value'])
            projectName("")
            propertyFile("")
            groovyScript("")
            groovyScriptFile("")
            bindings("")
            groovyClasspath("")
            propertyKey("")
            defaultValue(ccsm_default_params['cloud']['default_value'])
            defaultPropertyFile("")
            defaultGroovyScript("")
            defaultGroovyScriptFile("")
            defaultBindings("")
            defaultGroovyClasspath("")
            defaultPropertyKey("")
            descriptionPropertyValue(ccsm_default_params['cloud']['value_description'])
            descriptionPropertyFile("")
            descriptionGroovyScript("")
            descriptionGroovyScriptFile("")
            descriptionBindings("")
            descriptionGroovyClasspath("")
            descriptionPropertyKey("")
            javascriptFile("")
            javascript("")
            saveJSONParameterToFile(false)
            quoteValue(false)
            visibleItemCount(1)
            description("\n______________________________________________________________________________________________________\n")
            multiSelectDelimiter(',')
        }
        stringParam('EPC_RELEASE__TIME', "", "Format: yyyy-MM-dd HH:mm")
        stringParam('EPC_RELEASE__NFT_VERSION', ccsm_default_params['udm_nft_auto_version']['value'], "")
        stringParam('EPC_RELEASE__NFT_BRANCH', ccsm_default_params['nft_branch']['value'], "")
        stringParam('EPC_RELEASE__CCSM', ccsm_default_params['ccsm_package']['value'], "")
        stringParam('EPC_RELEASE__SMESH', ccsm_default_params['smesh_package']['value'], "")
        booleanParam("EPC_RELEASE__${ccsm_default_params['run_stability']['name']}", ccsm_default_params['run_stability']['value'].toBoolean(), "")
        booleanParam("EPC_RELEASE__${ccsm_default_params['run_maintainability']['name']}", ccsm_default_params['run_maintainability']['value'].toBoolean(), "")
        booleanParam("EPC_RELEASE__${ccsm_default_params['run_podsfaults']['name']}", ccsm_default_params['run_podsfaults']['value'].toBoolean(), "")
        booleanParam("EPC_RELEASE__${ccsm_default_params['run_commonfailures']['name']}", ccsm_default_params['run_commonfailures']['value'].toBoolean(), "")
        extendedChoice {
            name("EPC_RELEASE__CLOUD")
            type("PT_SINGLE_SELECT")
            value(cnhss_default_params['cloud']['value'])
            projectName("")
            propertyFile("")
            groovyScript("")
            groovyScriptFile("")
            bindings("")
            groovyClasspath("")
            propertyKey("")
            defaultValue(cnhss_default_params['cloud']['default_value'])
            defaultPropertyFile("")
            defaultGroovyScript("")
            defaultGroovyScriptFile("")
            defaultBindings("")
            defaultGroovyClasspath("")
            defaultPropertyKey("")
            descriptionPropertyValue(cnhss_default_params['cloud']['value_description'])
            descriptionPropertyFile("")
            descriptionGroovyScript("")
            descriptionGroovyScriptFile("")
            descriptionBindings("")
            descriptionGroovyClasspath("")
            descriptionPropertyKey("")
            javascriptFile("")
            javascript("")
            saveJSONParameterToFile(false)
            quoteValue(false)
            visibleItemCount(1)
            description("\n______________________________________________________________________________________________________\n")
            multiSelectDelimiter(',')
        }
        stringParam('EPC_INTERNAL__TIME', "", "Format: yyyy-MM-dd HH:mm")
        stringParam('EPC_INTERNAL__NFT_VERSION', ccsm_default_params['udm_nft_auto_version']['value'], "")
        stringParam('EPC_INTERNAL__NFT_BRANCH', ccsm_default_params['nft_branch']['value'], "")
        stringParam('EPC_INTERNAL__CCSM', ccsm_default_params['ccsm_package']['value'], "")
        stringParam('EPC_INTERNAL__SMESH', ccsm_default_params['smesh_package']['value'], "")
        booleanParam("EPC_INTERNAL__${ccsm_default_params['run_stability']['name']}", ccsm_default_params['run_stability']['value'].toBoolean(), "")
        booleanParam("EPC_INTERNAL__${ccsm_default_params['run_maintainability']['name']}", ccsm_default_params['run_maintainability']['value'].toBoolean(), "")
        booleanParam("EPC_INTERNAL__${ccsm_default_params['run_podsfaults']['name']}", ccsm_default_params['run_podsfaults']['value'].toBoolean(), "")
        booleanParam("EPC_INTERNAL__${ccsm_default_params['run_commonfailures']['name']}", ccsm_default_params['run_commonfailures']['value'].toBoolean(), "")
        extendedChoice {
            name("EPC_INTERNAL__CLOUD")
            type("PT_SINGLE_SELECT")
            value(cnhss_default_params['cloud']['value'])
            projectName("")
            propertyFile("")
            groovyScript("")
            groovyScriptFile("")
            bindings("")
            groovyClasspath("")
            propertyKey("")
            defaultValue(cnhss_default_params['cloud']['default_value'])
            defaultPropertyFile("")
            defaultGroovyScript("")
            defaultGroovyScriptFile("")
            defaultBindings("")
            defaultGroovyClasspath("")
            defaultPropertyKey("")
            descriptionPropertyValue(cnhss_default_params['cloud']['value_description'])
            descriptionPropertyFile("")
            descriptionGroovyScript("")
            descriptionGroovyScriptFile("")
            descriptionBindings("")
            descriptionGroovyClasspath("")
            descriptionPropertyKey("")
            javascriptFile("")
            javascript("")
            saveJSONParameterToFile(false)
            quoteValue(false)
            visibleItemCount(1)
            description("\n______________________________________________________________________________________________________\n")
            multiSelectDelimiter(',')
        }
        stringParam('IMS_RELEASE__TIME', "", "Format: yyyy-MM-dd HH:mm")
        stringParam('IMS_RELEASE__NFT_VERSION', ccsm_default_params['udm_nft_auto_version']['value'], "")
        stringParam('IMS_RELEASE__NFT_BRANCH', ccsm_default_params['nft_branch']['value'], "")
        stringParam('IMS_RELEASE__CCSM', ccsm_default_params['ccsm_package']['value'], "")
        stringParam('IMS_RELEASE__SMESH', ccsm_default_params['smesh_package']['value'], "")
        booleanParam("IMS_RELEASE__${ccsm_default_params['run_stability']['name']}", ccsm_default_params['run_stability']['value'].toBoolean(), "")
        booleanParam("IMS_RELEASE__${ccsm_default_params['run_maintainability']['name']}", ccsm_default_params['run_maintainability']['value'].toBoolean(), "")
        booleanParam("IMS_RELEASE__${ccsm_default_params['run_podsfaults']['name']}", ccsm_default_params['run_podsfaults']['value'].toBoolean(), "")
        booleanParam("IMS_RELEASE__${ccsm_default_params['run_commonfailures']['name']}", ccsm_default_params['run_commonfailures']['value'].toBoolean(), "")
        extendedChoice {
            name("IMS_RELEASE__CLOUD")
            type("PT_SINGLE_SELECT")
            value(cnhss_default_params['cloud']['value'])
            projectName("")
            propertyFile("")
            groovyScript("")
            groovyScriptFile("")
            bindings("")
            groovyClasspath("")
            propertyKey("")
            defaultValue(cnhss_default_params['cloud']['default_value'])
            defaultPropertyFile("")
            defaultGroovyScript("")
            defaultGroovyScriptFile("")
            defaultBindings("")
            defaultGroovyClasspath("")
            defaultPropertyKey("")
            descriptionPropertyValue(cnhss_default_params['cloud']['value_description'])
            descriptionPropertyFile("")
            descriptionGroovyScript("")
            descriptionGroovyScriptFile("")
            descriptionBindings("")
            descriptionGroovyClasspath("")
            descriptionPropertyKey("")
            javascriptFile("")
            javascript("")
            saveJSONParameterToFile(false)
            quoteValue(false)
            visibleItemCount(1)
            description("\n______________________________________________________________________________________________________\n")
            multiSelectDelimiter(',')
        }
        stringParam('IMS_INTERNAL__TIME', "", "Format: yyyy-MM-dd HH:mm")
        stringParam('IMS_INTERNAL__NFT_VERSION', ccsm_default_params['udm_nft_auto_version']['value'], "")
        stringParam('IMS_INTERNAL__NFT_BRANCH', ccsm_default_params['nft_branch']['value'], "")
        stringParam('IMS_INTERNAL__CCSM', ccsm_default_params['ccsm_package']['value'], "")
        stringParam('IMS_INTERNAL__SMESH', ccsm_default_params['smesh_package']['value'], "")
        booleanParam("IMS_INTERNAL__${ccsm_default_params['run_stability']['name']}", ccsm_default_params['run_stability']['value'].toBoolean(), "")
        booleanParam("IMS_INTERNAL__${ccsm_default_params['run_maintainability']['name']}", ccsm_default_params['run_maintainability']['value'].toBoolean(), "")
        booleanParam("IMS_INTERNAL__${ccsm_default_params['run_podsfaults']['name']}", ccsm_default_params['run_podsfaults']['value'].toBoolean(), "")
        booleanParam("IMS_INTERNAL__${ccsm_default_params['run_commonfailures']['name']}", ccsm_default_params['run_commonfailures']['value'].toBoolean(), "")
        extendedChoice {
            name("IMS_INTERNAL__CLOUD")
            type("PT_SINGLE_SELECT")
            value(cnhss_default_params['cloud']['value'])
            projectName("")
            propertyFile("")
            groovyScript("")
            groovyScriptFile("")
            bindings("")
            groovyClasspath("")
            propertyKey("")
            defaultValue(cnhss_default_params['cloud']['default_value'])
            defaultPropertyFile("")
            defaultGroovyScript("")
            defaultGroovyScriptFile("")
            defaultBindings("")
            defaultGroovyClasspath("")
            defaultPropertyKey("")
            descriptionPropertyValue(cnhss_default_params['cloud']['value_description'])
            descriptionPropertyFile("")
            descriptionGroovyScript("")
            descriptionGroovyScriptFile("")
            descriptionBindings("")
            descriptionGroovyClasspath("")
            descriptionPropertyKey("")
            javascriptFile("")
            javascript("")
            saveJSONParameterToFile(false)
            quoteValue(false)
            visibleItemCount(1)
            description("\n______________________________________________________________________________________________________\n")
            multiSelectDelimiter(',')
        }
        stringParam('RELEASE__TIME', "", "Format: yyyy-MM-dd HH:mm")
        stringParam('RELEASE__NFT_VERSION', ccsm_default_params['udm_nft_auto_version']['value'], "")
        stringParam('RELEASE__NFT_BRANCH', ccsm_default_params['nft_branch']['value'], "")
        stringParam('RELEASE__CCSM', ccsm_default_params['ccsm_package']['value'], "")
        stringParam('RELEASE__SMESH', ccsm_default_params['smesh_package']['value'], "")
        booleanParam("RELEASE__${ccsm_default_params['run_trafficmix']['name']}", ccsm_default_params['run_trafficmix']['value'].toBoolean(), "")
        booleanParam("RELEASE__${ccsm_default_params['run_stability']['name']}", ccsm_default_params['run_stability']['value'].toBoolean(), "")
        booleanParam("RELEASE__${ccsm_default_params['run_maintainability']['name']}", ccsm_default_params['run_maintainability']['value'].toBoolean(), "")
        booleanParam("RELEASE__${ccsm_default_params['run_robustness']['name']}", ccsm_default_params['run_robustness']['value'].toBoolean(), "")
        booleanParam("RELEASE__${ccsm_default_params['run_licenses']['name']}", ccsm_default_params['run_licenses']['value'].toBoolean(), "")
        booleanParam("RELEASE__${ccsm_default_params['run_overload_tcs']['name']}", ccsm_default_params['run_overload_tcs']['value'].toBoolean(), "")
        extendedChoice {
            name("RELEASE__CLOUD")
            type("PT_SINGLE_SELECT")
            value(ccsm_default_params['cloud']['value'])
            projectName("")
            propertyFile("")
            groovyScript("")
            groovyScriptFile("")
            bindings("")
            groovyClasspath("")
            propertyKey("")
            defaultValue(ccsm_default_params['cloud']['default_value'])
            defaultPropertyFile("")
            defaultGroovyScript("")
            defaultGroovyScriptFile("")
            defaultBindings("")
            defaultGroovyClasspath("")
            defaultPropertyKey("")
            descriptionPropertyValue(ccsm_default_params['cloud']['value_description'])
            descriptionPropertyFile("")
            descriptionGroovyScript("")
            descriptionGroovyScriptFile("")
            descriptionBindings("")
            descriptionGroovyClasspath("")
            descriptionPropertyKey("")
            javascriptFile("")
            javascript("")
            saveJSONParameterToFile(false)
            quoteValue(false)
            visibleItemCount(1)
            description("\n______________________________________________________________________________________________________\n")
            multiSelectDelimiter(',')
        }
        stringParam('RELEASE_WF__TIME', "", "Format: yyyy-MM-dd HH:mm")
        stringParam('RELEASE_WF__NFT_VERSION', ccsm_default_params['udm_nft_auto_version']['value'], "")
        stringParam('RELEASE_WF__NFT_BRANCH', ccsm_default_params['nft_branch']['value'], "")
        stringParam('RELEASE_WF__EVNFM_SERVER_NAME', ccsm_default_params['evnfm_server_name']['value'], "")
        stringParam('RELEASE_WF__CSAR_URL', ccsm_default_params['csar_url']['value'], "")
        stringParam('RELEASE_WF__CSAR_PATH', ccsm_default_params['csar_path']['value'], "")
        stringParam('RELEASE_WF__CSAR_VERSION', ccsm_default_params['csar_version']['value'], "")
        stringParam('RELEASE_WF__WF_CCSM_VERSION', ccsm_default_params['wf_ccsm_version']['value'], "")
        booleanParam("RELEASE_WF__${ccsm_default_params['run_trafficmix']['name']}", ccsm_default_params['run_trafficmix']['value'].toBoolean(), "")
        booleanParam("RELEASE_WF__${ccsm_default_params['run_stability']['name']}", ccsm_default_params['run_stability']['value'].toBoolean(), "")
        booleanParam("RELEASE_WF__${ccsm_default_params['run_maintainability']['name']}", ccsm_default_params['run_maintainability']['value'].toBoolean(), "")
        booleanParam("RELEASE_WF__${ccsm_default_params['run_robustness']['name']}", ccsm_default_params['run_robustness']['value'].toBoolean(), "")
        booleanParam("RELEASE_WF__${ccsm_default_params['run_licenses']['name']}", ccsm_default_params['run_licenses']['value'].toBoolean(), "")
        booleanParam("RELEASE_WF__${ccsm_default_params['run_overload_tcs']['name']}", ccsm_default_params['run_overload_tcs']['value'].toBoolean(), "")
        booleanParam("RELEASE_WF__${ccsm_default_params['run_scaling']['name']}", ccsm_default_params['run_scaling']['value'].toBoolean(), "")
        booleanParam("RELEASE_WF__${ccsm_default_params['run_update']['name']}", ccsm_default_params['run_update']['value'].toBoolean(), "")
        stringParam('RELEASE_WF__CSAR_UPGRADE_PATH', ccsm_default_params['csar_upgrade_path']['value'], "")
        stringParam('RELEASE_WF__CSAR_UPGRADE_VERSION', ccsm_default_params['csar_upgrade_version']['value'], "")
        stringParam('RELEASE_WF__WF_CCSM_UPGRADE_VERSION', ccsm_default_params['wf_ccsm_upgrade_version']['value'], "")
        extendedChoice {
            name("RELEASE_WF__CLOUD")
            type("PT_SINGLE_SELECT")
            value(ccsm_default_params['cloud']['value'])
            projectName("")
            propertyFile("")
            groovyScript("")
            groovyScriptFile("")
            bindings("")
            groovyClasspath("")
            propertyKey("")
            defaultValue(ccsm_default_params['cloud']['default_value'])
            defaultPropertyFile("")
            defaultGroovyScript("")
            defaultGroovyScriptFile("")
            defaultBindings("")
            defaultGroovyClasspath("")
            defaultPropertyKey("")
            descriptionPropertyValue(ccsm_default_params['cloud']['value_description'])
            descriptionPropertyFile("")
            descriptionGroovyScript("")
            descriptionGroovyScriptFile("")
            descriptionBindings("")
            descriptionGroovyClasspath("")
            descriptionPropertyKey("")
            javascriptFile("")
            javascript("")
            saveJSONParameterToFile(false)
            quoteValue(false)
            visibleItemCount(1)
            description("\n______________________________________________________________________________________________________\n")
            multiSelectDelimiter(',')
        }
        stringParam('INTERNAL__TIME', "", "Format: yyyy-MM-dd HH:mm")
        stringParam('INTERNAL__NFT_VERSION', ccsm_default_params['udm_nft_auto_version']['value'], "")
        stringParam('INTERNAL__NFT_BRANCH', ccsm_default_params['nft_branch']['value'], "")
        stringParam('INTERNAL__CCSM', ccsm_default_params['ccsm_package']['value'], "")
        stringParam('INTERNAL__SMESH', ccsm_default_params['smesh_package']['value'], "")
        booleanParam("INTERNAL__${ccsm_default_params['run_trafficmix']['name']}", ccsm_default_params['run_trafficmix']['value'].toBoolean(), "")
        booleanParam("INTERNAL__${ccsm_default_params['run_stability']['name']}", ccsm_default_params['run_stability']['value'].toBoolean(), "")
        booleanParam("INTERNAL__${ccsm_default_params['run_maintainability']['name']}", ccsm_default_params['run_maintainability']['value'].toBoolean(), "")
        booleanParam("INTERNAL__RUN_ROBUSTNESS_INTERNAL", true, "")
        booleanParam("INTERNAL__RUN_ROBUSTNESS_INPROGRESS", ccsm_default_params['run_robustness']['value'].toBoolean(), "")
        booleanParam("INTERNAL__RUN_ROBUSTNESS_RELEASE", ccsm_default_params['run_robustness']['value'].toBoolean(), "")
        booleanParam("INTERNAL__${ccsm_default_params['run_licenses']['name']}", ccsm_default_params['run_licenses']['value'].toBoolean(), "")
        booleanParam("INTERNAL__RUN_OVERLOAD_TCS_INTERNAL", false, "")
        booleanParam("INTERNAL__RUN_OVERLOAD_TCS_INPROGRESS", false, "")
        extendedChoice {
            name("INTERNAL__CLOUD")
            type("PT_SINGLE_SELECT")
            value(ccsm_default_params['cloud']['value'])
            projectName("PROJECT_NAME")
            propertyFile("")
            groovyScript("")
            groovyScriptFile("")
            bindings("")
            groovyClasspath("")
            propertyKey("")
            defaultValue(ccsm_default_params['cloud']['default_value'])
            defaultPropertyFile("")
            defaultGroovyScript("")
            defaultGroovyScriptFile("")
            defaultBindings("")
            defaultGroovyClasspath("")
            defaultPropertyKey("")
            descriptionPropertyValue(ccsm_default_params['cloud']['value_description'])
            descriptionPropertyFile("")
            descriptionGroovyScript("")
            descriptionGroovyScriptFile("")
            descriptionBindings("")
            descriptionGroovyClasspath("")
            descriptionPropertyKey("")
            javascriptFile("")
            javascript("")
            saveJSONParameterToFile(false)
            quoteValue(false)
            visibleItemCount(1)
            description("")
            multiSelectDelimiter(',')
        }
    }

    definition {
        cps {
            sandbox(true)
            script('''
@Library("PipelineNft5gLibrary") _

dailyTriggers {}
''')
        }
    }
}
